---
- name: Generate the sos report
  hosts: all
  gather_facts: false
  vars:
    CASE_ID: 12345
    tmp_dir: /tmp
  tasks:
      - name: check memory_utilization %
        shell: free -t | awk 'FNR == 2 {printf("%.2f"), $3/$2*100}'
        register: memory_utilization
